Repository terraform-redhat/terraform-aws-rosa-sts, pull requests merged in 2023-07, with the labels that each got.

#22 OCM-2361 Support generated account_role_prefix
  README.md
  account_roles_creation/README.md
  account_roles_creation/main.tf
  account_roles_creation/output.tf
  examples/account_roles/variables.tf
  output.tf
Labels: approved, lgtm

#24 OCM-2415: Validating the OCP version in create_account_roles module
  README.md
  examples/operator_roles_and_oidc/create_rosa_sts_operator_roles_and_oidc.tf
  main.tf
  output.tf
  variables.tf
Labels: approved, lgtm, jira/valid-reference

#19 Update put_objects_in_s3_bucket.tf
  oidc_config_resources/put_objects_in_s3_bucket.tf
Labels: approved, lgtm, ok-to-test

#26 OCM-2415: Supporting creating account roles with minor versions only
  main.tf
  variables.tf
Labels: approved, lgtm, jira/valid-reference
